/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppTeamIndexRouteImport } from './routes/app/team/index'
import { Route as AppSettingsIndexRouteImport } from './routes/app/settings/index'
import { Route as AppQuotesIndexRouteImport } from './routes/app/quotes/index'
import { Route as AppProjectsIndexRouteImport } from './routes/app/projects/index'
import { Route as AppOverheadIndexRouteImport } from './routes/app/overhead/index'
import { Route as AppLifecycleIndexRouteImport } from './routes/app/lifecycle/index'
import { Route as AppExpensesIndexRouteImport } from './routes/app/expenses/index'
import { Route as AppDashboardIndexRouteImport } from './routes/app/dashboard/index'
import { Route as AppAnalyticsIndexRouteImport } from './routes/app/analytics/index'
import { Route as ApiQuotesIndexRouteImport } from './routes/api/quotes/index'
import { Route as ApiExpensesIndexRouteImport } from './routes/api/expenses/index'
import { Route as ApiQuotesSettingsRouteImport } from './routes/api/quotes/settings'
import { Route as ApiQuotesCalculateRouteImport } from './routes/api/quotes/calculate'
import { Route as ApiQuotesIdRouteImport } from './routes/api/quotes/$id'
import { Route as ApiExpensesIdRouteImport } from './routes/api/expenses/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppExpensesCategoriesIndexRouteImport } from './routes/app/expenses/categories/index'
import { Route as ApiOverheadCostsIndexRouteImport } from './routes/api/overhead/costs/index'
import { Route as ApiOverheadCategoriesIndexRouteImport } from './routes/api/overhead/categories/index'
import { Route as ApiExpensesCategoriesIndexRouteImport } from './routes/api/expenses/categories/index'
import { Route as ApiOverheadCostsIdRouteImport } from './routes/api/overhead/costs/$id'
import { Route as ApiExpensesCategoriesIdRouteImport } from './routes/api/expenses/categories/$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTeamIndexRoute = AppTeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppQuotesIndexRoute = AppQuotesIndexRouteImport.update({
  id: '/quotes/',
  path: '/quotes/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOverheadIndexRoute = AppOverheadIndexRouteImport.update({
  id: '/overhead/',
  path: '/overhead/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLifecycleIndexRoute = AppLifecycleIndexRouteImport.update({
  id: '/lifecycle/',
  path: '/lifecycle/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExpensesIndexRoute = AppExpensesIndexRouteImport.update({
  id: '/expenses/',
  path: '/expenses/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAnalyticsIndexRoute = AppAnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiQuotesIndexRoute = ApiQuotesIndexRouteImport.update({
  id: '/api/quotes/',
  path: '/api/quotes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExpensesIndexRoute = ApiExpensesIndexRouteImport.update({
  id: '/api/expenses/',
  path: '/api/expenses/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuotesSettingsRoute = ApiQuotesSettingsRouteImport.update({
  id: '/api/quotes/settings',
  path: '/api/quotes/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuotesCalculateRoute = ApiQuotesCalculateRouteImport.update({
  id: '/api/quotes/calculate',
  path: '/api/quotes/calculate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuotesIdRoute = ApiQuotesIdRouteImport.update({
  id: '/api/quotes/$id',
  path: '/api/quotes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExpensesIdRoute = ApiExpensesIdRouteImport.update({
  id: '/api/expenses/$id',
  path: '/api/expenses/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppExpensesCategoriesIndexRoute =
  AppExpensesCategoriesIndexRouteImport.update({
    id: '/expenses/categories/',
    path: '/expenses/categories/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const ApiOverheadCostsIndexRoute = ApiOverheadCostsIndexRouteImport.update({
  id: '/api/overhead/costs/',
  path: '/api/overhead/costs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOverheadCategoriesIndexRoute =
  ApiOverheadCategoriesIndexRouteImport.update({
    id: '/api/overhead/categories/',
    path: '/api/overhead/categories/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiExpensesCategoriesIndexRoute =
  ApiExpensesCategoriesIndexRouteImport.update({
    id: '/api/expenses/categories/',
    path: '/api/expenses/categories/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOverheadCostsIdRoute = ApiOverheadCostsIdRouteImport.update({
  id: '/api/overhead/costs/$id',
  path: '/api/overhead/costs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExpensesCategoriesIdRoute = ApiExpensesCategoriesIdRouteImport.update({
  id: '/api/expenses/categories/$id',
  path: '/api/expenses/categories/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/expenses/$id': typeof ApiExpensesIdRoute
  '/api/quotes/$id': typeof ApiQuotesIdRoute
  '/api/quotes/calculate': typeof ApiQuotesCalculateRoute
  '/api/quotes/settings': typeof ApiQuotesSettingsRoute
  '/api/expenses/': typeof ApiExpensesIndexRoute
  '/api/quotes/': typeof ApiQuotesIndexRoute
  '/app/analytics/': typeof AppAnalyticsIndexRoute
  '/app/dashboard/': typeof AppDashboardIndexRoute
  '/app/expenses/': typeof AppExpensesIndexRoute
  '/app/lifecycle/': typeof AppLifecycleIndexRoute
  '/app/overhead/': typeof AppOverheadIndexRoute
  '/app/projects/': typeof AppProjectsIndexRoute
  '/app/quotes/': typeof AppQuotesIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/team/': typeof AppTeamIndexRoute
  '/api/expenses/categories/$id': typeof ApiExpensesCategoriesIdRoute
  '/api/overhead/costs/$id': typeof ApiOverheadCostsIdRoute
  '/api/expenses/categories/': typeof ApiExpensesCategoriesIndexRoute
  '/api/overhead/categories/': typeof ApiOverheadCategoriesIndexRoute
  '/api/overhead/costs/': typeof ApiOverheadCostsIndexRoute
  '/app/expenses/categories/': typeof AppExpensesCategoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/expenses/$id': typeof ApiExpensesIdRoute
  '/api/quotes/$id': typeof ApiQuotesIdRoute
  '/api/quotes/calculate': typeof ApiQuotesCalculateRoute
  '/api/quotes/settings': typeof ApiQuotesSettingsRoute
  '/api/expenses': typeof ApiExpensesIndexRoute
  '/api/quotes': typeof ApiQuotesIndexRoute
  '/app/analytics': typeof AppAnalyticsIndexRoute
  '/app/dashboard': typeof AppDashboardIndexRoute
  '/app/expenses': typeof AppExpensesIndexRoute
  '/app/lifecycle': typeof AppLifecycleIndexRoute
  '/app/overhead': typeof AppOverheadIndexRoute
  '/app/projects': typeof AppProjectsIndexRoute
  '/app/quotes': typeof AppQuotesIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/app/team': typeof AppTeamIndexRoute
  '/api/expenses/categories/$id': typeof ApiExpensesCategoriesIdRoute
  '/api/overhead/costs/$id': typeof ApiOverheadCostsIdRoute
  '/api/expenses/categories': typeof ApiExpensesCategoriesIndexRoute
  '/api/overhead/categories': typeof ApiOverheadCategoriesIndexRoute
  '/api/overhead/costs': typeof ApiOverheadCostsIndexRoute
  '/app/expenses/categories': typeof AppExpensesCategoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/expenses/$id': typeof ApiExpensesIdRoute
  '/api/quotes/$id': typeof ApiQuotesIdRoute
  '/api/quotes/calculate': typeof ApiQuotesCalculateRoute
  '/api/quotes/settings': typeof ApiQuotesSettingsRoute
  '/api/expenses/': typeof ApiExpensesIndexRoute
  '/api/quotes/': typeof ApiQuotesIndexRoute
  '/app/analytics/': typeof AppAnalyticsIndexRoute
  '/app/dashboard/': typeof AppDashboardIndexRoute
  '/app/expenses/': typeof AppExpensesIndexRoute
  '/app/lifecycle/': typeof AppLifecycleIndexRoute
  '/app/overhead/': typeof AppOverheadIndexRoute
  '/app/projects/': typeof AppProjectsIndexRoute
  '/app/quotes/': typeof AppQuotesIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/team/': typeof AppTeamIndexRoute
  '/api/expenses/categories/$id': typeof ApiExpensesCategoriesIdRoute
  '/api/overhead/costs/$id': typeof ApiOverheadCostsIdRoute
  '/api/expenses/categories/': typeof ApiExpensesCategoriesIndexRoute
  '/api/overhead/categories/': typeof ApiOverheadCategoriesIndexRoute
  '/api/overhead/costs/': typeof ApiOverheadCostsIndexRoute
  '/app/expenses/categories/': typeof AppExpensesCategoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/app/'
    | '/api/auth/$'
    | '/api/expenses/$id'
    | '/api/quotes/$id'
    | '/api/quotes/calculate'
    | '/api/quotes/settings'
    | '/api/expenses/'
    | '/api/quotes/'
    | '/app/analytics/'
    | '/app/dashboard/'
    | '/app/expenses/'
    | '/app/lifecycle/'
    | '/app/overhead/'
    | '/app/projects/'
    | '/app/quotes/'
    | '/app/settings/'
    | '/app/team/'
    | '/api/expenses/categories/$id'
    | '/api/overhead/costs/$id'
    | '/api/expenses/categories/'
    | '/api/overhead/categories/'
    | '/api/overhead/costs/'
    | '/app/expenses/categories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/app'
    | '/api/auth/$'
    | '/api/expenses/$id'
    | '/api/quotes/$id'
    | '/api/quotes/calculate'
    | '/api/quotes/settings'
    | '/api/expenses'
    | '/api/quotes'
    | '/app/analytics'
    | '/app/dashboard'
    | '/app/expenses'
    | '/app/lifecycle'
    | '/app/overhead'
    | '/app/projects'
    | '/app/quotes'
    | '/app/settings'
    | '/app/team'
    | '/api/expenses/categories/$id'
    | '/api/overhead/costs/$id'
    | '/api/expenses/categories'
    | '/api/overhead/categories'
    | '/api/overhead/costs'
    | '/app/expenses/categories'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/app/'
    | '/api/auth/$'
    | '/api/expenses/$id'
    | '/api/quotes/$id'
    | '/api/quotes/calculate'
    | '/api/quotes/settings'
    | '/api/expenses/'
    | '/api/quotes/'
    | '/app/analytics/'
    | '/app/dashboard/'
    | '/app/expenses/'
    | '/app/lifecycle/'
    | '/app/overhead/'
    | '/app/projects/'
    | '/app/quotes/'
    | '/app/settings/'
    | '/app/team/'
    | '/api/expenses/categories/$id'
    | '/api/overhead/costs/$id'
    | '/api/expenses/categories/'
    | '/api/overhead/categories/'
    | '/api/overhead/costs/'
    | '/app/expenses/categories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiExpensesIdRoute: typeof ApiExpensesIdRoute
  ApiQuotesIdRoute: typeof ApiQuotesIdRoute
  ApiQuotesCalculateRoute: typeof ApiQuotesCalculateRoute
  ApiQuotesSettingsRoute: typeof ApiQuotesSettingsRoute
  ApiExpensesIndexRoute: typeof ApiExpensesIndexRoute
  ApiQuotesIndexRoute: typeof ApiQuotesIndexRoute
  ApiExpensesCategoriesIdRoute: typeof ApiExpensesCategoriesIdRoute
  ApiOverheadCostsIdRoute: typeof ApiOverheadCostsIdRoute
  ApiExpensesCategoriesIndexRoute: typeof ApiExpensesCategoriesIndexRoute
  ApiOverheadCategoriesIndexRoute: typeof ApiOverheadCategoriesIndexRoute
  ApiOverheadCostsIndexRoute: typeof ApiOverheadCostsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/team/': {
      id: '/app/team/'
      path: '/team'
      fullPath: '/app/team/'
      preLoaderRoute: typeof AppTeamIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/settings'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/quotes/': {
      id: '/app/quotes/'
      path: '/quotes'
      fullPath: '/app/quotes/'
      preLoaderRoute: typeof AppQuotesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/projects/': {
      id: '/app/projects/'
      path: '/projects'
      fullPath: '/app/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/overhead/': {
      id: '/app/overhead/'
      path: '/overhead'
      fullPath: '/app/overhead/'
      preLoaderRoute: typeof AppOverheadIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/lifecycle/': {
      id: '/app/lifecycle/'
      path: '/lifecycle'
      fullPath: '/app/lifecycle/'
      preLoaderRoute: typeof AppLifecycleIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/expenses/': {
      id: '/app/expenses/'
      path: '/expenses'
      fullPath: '/app/expenses/'
      preLoaderRoute: typeof AppExpensesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dashboard/': {
      id: '/app/dashboard/'
      path: '/dashboard'
      fullPath: '/app/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/analytics/': {
      id: '/app/analytics/'
      path: '/analytics'
      fullPath: '/app/analytics/'
      preLoaderRoute: typeof AppAnalyticsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/quotes/': {
      id: '/api/quotes/'
      path: '/api/quotes'
      fullPath: '/api/quotes/'
      preLoaderRoute: typeof ApiQuotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/expenses/': {
      id: '/api/expenses/'
      path: '/api/expenses'
      fullPath: '/api/expenses/'
      preLoaderRoute: typeof ApiExpensesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quotes/settings': {
      id: '/api/quotes/settings'
      path: '/api/quotes/settings'
      fullPath: '/api/quotes/settings'
      preLoaderRoute: typeof ApiQuotesSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quotes/calculate': {
      id: '/api/quotes/calculate'
      path: '/api/quotes/calculate'
      fullPath: '/api/quotes/calculate'
      preLoaderRoute: typeof ApiQuotesCalculateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quotes/$id': {
      id: '/api/quotes/$id'
      path: '/api/quotes/$id'
      fullPath: '/api/quotes/$id'
      preLoaderRoute: typeof ApiQuotesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/expenses/$id': {
      id: '/api/expenses/$id'
      path: '/api/expenses/$id'
      fullPath: '/api/expenses/$id'
      preLoaderRoute: typeof ApiExpensesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/expenses/categories/': {
      id: '/app/expenses/categories/'
      path: '/expenses/categories'
      fullPath: '/app/expenses/categories/'
      preLoaderRoute: typeof AppExpensesCategoriesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/overhead/costs/': {
      id: '/api/overhead/costs/'
      path: '/api/overhead/costs'
      fullPath: '/api/overhead/costs/'
      preLoaderRoute: typeof ApiOverheadCostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/overhead/categories/': {
      id: '/api/overhead/categories/'
      path: '/api/overhead/categories'
      fullPath: '/api/overhead/categories/'
      preLoaderRoute: typeof ApiOverheadCategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/expenses/categories/': {
      id: '/api/expenses/categories/'
      path: '/api/expenses/categories'
      fullPath: '/api/expenses/categories/'
      preLoaderRoute: typeof ApiExpensesCategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/overhead/costs/$id': {
      id: '/api/overhead/costs/$id'
      path: '/api/overhead/costs/$id'
      fullPath: '/api/overhead/costs/$id'
      preLoaderRoute: typeof ApiOverheadCostsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/expenses/categories/$id': {
      id: '/api/expenses/categories/$id'
      path: '/api/expenses/categories/$id'
      fullPath: '/api/expenses/categories/$id'
      preLoaderRoute: typeof ApiExpensesCategoriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAnalyticsIndexRoute: typeof AppAnalyticsIndexRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppExpensesIndexRoute: typeof AppExpensesIndexRoute
  AppLifecycleIndexRoute: typeof AppLifecycleIndexRoute
  AppOverheadIndexRoute: typeof AppOverheadIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppQuotesIndexRoute: typeof AppQuotesIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppTeamIndexRoute: typeof AppTeamIndexRoute
  AppExpensesCategoriesIndexRoute: typeof AppExpensesCategoriesIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAnalyticsIndexRoute: AppAnalyticsIndexRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppExpensesIndexRoute: AppExpensesIndexRoute,
  AppLifecycleIndexRoute: AppLifecycleIndexRoute,
  AppOverheadIndexRoute: AppOverheadIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppQuotesIndexRoute: AppQuotesIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppTeamIndexRoute: AppTeamIndexRoute,
  AppExpensesCategoriesIndexRoute: AppExpensesCategoriesIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiExpensesIdRoute: ApiExpensesIdRoute,
  ApiQuotesIdRoute: ApiQuotesIdRoute,
  ApiQuotesCalculateRoute: ApiQuotesCalculateRoute,
  ApiQuotesSettingsRoute: ApiQuotesSettingsRoute,
  ApiExpensesIndexRoute: ApiExpensesIndexRoute,
  ApiQuotesIndexRoute: ApiQuotesIndexRoute,
  ApiExpensesCategoriesIdRoute: ApiExpensesCategoriesIdRoute,
  ApiOverheadCostsIdRoute: ApiOverheadCostsIdRoute,
  ApiExpensesCategoriesIndexRoute: ApiExpensesCategoriesIndexRoute,
  ApiOverheadCategoriesIndexRoute: ApiOverheadCategoriesIndexRoute,
  ApiOverheadCostsIndexRoute: ApiOverheadCostsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
